### ISSUE TITLE
Make the project file structure more simple

### ISSUE THREAD

**Issue by JaakDragon** [ShibamRoy9826/Conversafe#2]
Make some changes to the file structure for more simple.
I was having difficulty to find the backend and frontend files.

**Comment by ShibamRoy9826** [comment]
I think its pretty much well organised and as per the traditional django structure. I am closing the issue for now, reopen it if you think there's something of a more specific change into the file structure or you can open a PR.

**Comment by JaakDragon** [comment]
ok
